### ISSUE TITLE
Aggregation changes

### ISSUE THREAD

**Issue by liorkesos** [linnovate/meanio#22]
We have several issues which we need to address in the aggregation area for stabalizing the package support and for making debugging easier and clearer in the development phase.

*JS Injection requirement*
1. Inplace js injection: In October 10th - @veljkopopovic helped me resolve a situation in which we saw white page errors (arghh drupal wsod :) ) on the installation of the gmap packge.
He found the the use of the way we injected the headerJS untill 55458ca82a3f373ab2cddebba9ef74bc0fe8104e caused this error.
2. Once we moved from " <script type="text/javascript">{{headerJs|raw}}</script>" to "<script type="text/javascript" src="/modules/aggregated.js?group=header"></script>" we resolved the issue but the ga and gmap packages that need to inject js inline do not work.
3. What this means is that we need to have an "inline" group in aggregation to enable injection of scripts that would run a document.write to build the retrieval of another remote script (like is common in google stuff)

*"Disable aggregation in dev mode"*
We have a recurring theme @andrija-hers has also talked with devs about regarding "disabling aggregation" for dev env - I think that upon building we should go over all of the scripts that used to be part of the aggregated object which is iterated in sortAggregateAssetsByWeight here - https://github.com/linnovate/meanio/blob/master/lib/aggregation.js
Maybe we can have a check in line 141 of https://github.com/linnovate/meanio/blob/master/lib/bootstrap.js which will see if we are in debug true and if so instead of "enabling the aggregation module" we will enable a different module (inclusion ?) which will simply iterate in system/server/views/include/head.html and simply place a sequence of script tags.

@andrija-hers @veljkopopovic does this seem reasonable?

**Comment by ADSKLowenthal** [comment]
@liorkesos We've removed aggregation in the latest versions of MeanIO/Mean. Can we close this issue?
