### ISSUE TITLE
aggregateAsset css should rewrite relative urls to maintain resource references

### ISSUE THREAD

**Issue by fracmak** [linnovate/meanio#28]
right now unless you're using absolute urls, images/fonts/etc break because they're expecting resources to be served from /public/asset/css/ but instead they're serving from /modules/

**Comment by ADSKLowenthal** [comment]
@timelf123 @liorkesos Aggregation is being handled by webpack, is this issue still valid or should it be closed?

**Comment by liorkesos** [comment]
We should close.
