### ISSUE TITLE
Compression on production

### ISSUE THREAD

**Issue by AlmogBaku** [linnovate/meanio#32]
see https://github.com/linnovate/mean/issues/753

https://github.com/expressjs/compression

**Comment by liorkesos** [comment]
Hi guys -what is the verdict on this @pratik60 can you prepare an organized PR?

**Comment by pratik60** [comment]
@liorkesos - Please close this. Its not the right issue, the correct issue is here => https://github.com/linnovate/mean/issues/753

Creating PR on both mean and meanio, and sending it in 10 minutes

**Comment by ADSKLowenthal** [comment]
@liorkesos Looks like this was resolved, and possibly not relevant anymore with the use of web pack.
