### ISSUE TITLE
doesn't install on ubuntu 14.04 lts

### ISSUE THREAD

**Issue by Maiti** [linnovate/meanio#39]
<h2><b>install into the mean io application console log:</b></h2>

<b>sudo npm install meanio</b>
WARN engine meanio@0.7.1: wanted: {"node":"0.10.x","npm":"1.4.x"} (current: {"node":"0.10.33","npm":"2.4.1"})

> meanio@0.7.1 preinstall /home/localhost/leed/node_modules/meanio
> node ./scripts/preinstall

WARN engine mean-cli@0.9.19: wanted: {"node":"0.10.x","npm":"2.1.x"} (current: {"node":"0.10.33","npm":"2.4.1"})

> mean-health@0.1.7 postinstall /home/localhost/leed/node_modules/meanio/node_modules/mean-health
> node ./postinstall.js

 
> mean-cli@0.9.19 preinstall /home/localhost/leed/node_modules/meanio/node_modules/mean-cli
> node ./scripts/preinstall

-
> meanio@0.7.1 postinstall /home/localhost/leed/node_modules/meanio
> cd ./lib/core_modules/server && npm install && cd ../../..

npm WARN package.json server@ No description
npm WARN package.json server@ No repository field.
npm WARN package.json server@ No README data
npm WARN locking Error: EACCES, open '/home/ed/.npm/_locks/connect-mongo-fa583c62d6797034.lock'
npm WARN locking  /home/ed/.npm/_locks/connect-mongo-fa583c62d6797034.lock failed { [Error: EACCES, open '/home/ed/.npm/_locks/connect-mongo-fa583c62d6797034.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ed/.npm/_locks/connect-mongo-fa583c62d6797034.lock' }
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1

npm ERR! Attempt to unlock /home/localhost/leed/node_modules/meanio/lib/core_modules/server/node_modules/connect-mongo, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ed/.npm/_locks/express-session-f7580be6d59a1574.lock'
npm WARN locking  /home/ed/.npm/_locks/express-session-f7580be6d59a1574.lock failed { [Error: EACCES, open '/home/ed/.npm/_locks/express-session-f7580be6d59a1574.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ed/.npm/_locks/express-session-f7580be6d59a1574.lock' }
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1

npm ERR! Attempt to unlock /home/localhost/leed/node_modules/meanio/lib/core_modules/server/node_modules/express-session, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ed/.npm/_locks/cookie-parser-5517877a04f59f52.lock'
npm WARN locking  /home/ed/.npm/_locks/cookie-parser-5517877a04f59f52.lock failed { [Error: EACCES, open '/home/ed/.npm/_locks/cookie-parser-5517877a04f59f52.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ed/.npm/_locks/cookie-parser-5517877a04f59f52.lock' }
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1

npm ERR! Attempt to unlock /home/localhost/leed/node_modules/meanio/lib/core_modules/server/node_modules/cookie-parser, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ed/.npm/_locks/express-validator-f463f84ef39e2c16.lock'
npm WARN locking  /home/ed/.npm/_locks/express-validator-f463f84ef39e2c16.lock failed { [Error: EACCES, open '/home/ed/.npm/_locks/express-validator-f463f84ef39e2c16.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ed/.npm/_locks/express-validator-f463f84ef39e2c16.lock' }
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1

npm ERR! Attempt to unlock /home/localhost/leed/node_modules/meanio/lib/core_modules/server/node_modules/express-validator, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ed/.npm/_locks/express-a097107ccc4c6510.lock'
npm WARN locking  /home/ed/.npm/_locks/express-a097107ccc4c6510.lock failed { [Error: EACCES, open '/home/ed/.npm/_locks/express-a097107ccc4c6510.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ed/.npm/_locks/express-a097107ccc4c6510.lock' }
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1

npm ERR! Attempt to unlock /home/localhost/leed/node_modules/meanio/lib/core_modules/server/node_modules/express, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ed/.npm/_locks/gridfs-stream-1ae171dc8090ca8a.lock'
npm WARN locking  /home/ed/.npm/_locks/gridfs-stream-1ae171dc8090ca8a.lock failed { [Error: EACCES, open '/home/ed/.npm/_locks/gridfs-stream-1ae171dc8090ca8a.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ed/.npm/_locks/gridfs-stream-1ae171dc8090ca8a.lock' }
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1

npm ERR! Attempt to unlock /home/localhost/leed/node_modules/meanio/lib/core_modules/server/node_modules/gridfs-stream, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ed/.npm/_locks/passport-ceab68f8f0b792f1.lock'
npm WARN locking  /home/ed/.npm/_locks/passport-ceab68f8f0b792f1.lock failed { [Error: EACCES, open '/home/ed/.npm/_locks/passport-ceab68f8f0b792f1.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ed/.npm/_locks/passport-ceab68f8f0b792f1.lock' }
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1

npm ERR! Attempt to unlock /home/localhost/leed/node_modules/meanio/lib/core_modules/server/node_modules/passport, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/ed/.npm/_locks/method-override-0736fddfe2bf38f1.lock'
npm WARN locking  /home/ed/.npm/_locks/method-override-0736fddfe2bf38f1.lock failed { [Error: EACCES, open '/home/ed/.npm/_locks/method-override-0736fddfe2bf38f1.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/ed/.npm/_locks/method-override-0736fddfe2bf38f1.lock' }
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1

npm ERR! Attempt to unlock /home/localhost/leed/node_modules/meanio/lib/core_modules/server/node_modules/method-override, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/localhost/leed/node_modules/meanio/lib/core_modules/server/npm-debug.log
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "meanio"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! meanio@0.7.1 postinstall: `cd ./lib/core_modules/server && npm install && cd ../../..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meanio@0.7.1 postinstall script 'cd ./lib/core_modules/server && npm install && cd ../../..'.
npm ERR! This is most likely a problem with the meanio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/localhost/leed/npm-debug.log

<h2>intall into the clear dir debug.log:</h2>

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install', 'meanio' ]
2 info using npm@2.4.1
3 info using node@v0.10.33
4 verbose node symlink /usr/bin/node
5 silly cache add args [ 'meanio', null ]
6 verbose cache add spec meanio
7 silly cache add parsed spec { raw: 'meanio',
7 silly cache add   scope: null,
7 silly cache add   name: 'meanio',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed meanio@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'meanio', range: '*', hasData: false }
12 silly mapToRegistry name meanio
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/meanio
16 verbose addNameRange registry:https://registry.npmjs.org/meanio not in flight; fetching
17 verbose request uri https://registry.npmjs.org/meanio
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:16:40
20 verbose request id 6e0b745a5da48317
21 verbose etag "CM091VG26VHJS5BXHNTISXGY9"
22 http request GET https://registry.npmjs.org/meanio
23 http 304 https://registry.npmjs.org/meanio
24 silly get cb [ 304,
24 silly get   { date: 'Sat, 31 Jan 2015 09:16:40 GMT',
24 silly get     server: 'Apache',
24 silly get     via: '1.1 varnish',
24 silly get     'last-modified': 'Sat, 31 Jan 2015 09:16:40 GMT',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"CM091VG26VHJS5BXHNTISXGY9"',
24 silly get     age: '0',
24 silly get     'x-served-by': 'cache-fra1223-FRA',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1422695800.617025,VS0,VE100',
24 silly get     vary: 'Accept',
24 silly get     'content-length': '0',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose etag https://registry.npmjs.org/meanio from cache
26 verbose get saving meanio to /home/ed/.npm/registry.npmjs.org/meanio/.cache.json
27 silly addNameRange number 2 { name: 'meanio', range: '*', hasData: true }
28 silly addNameRange versions [ 'meanio',
28 silly addNameRange   [ '0.0.1',
28 silly addNameRange     '0.0.2',
28 silly addNameRange     '0.0.3',
28 silly addNameRange     '0.0.4',
28 silly addNameRange     '0.0.5',
28 silly addNameRange     '0.0.6',
28 silly addNameRange     '0.0.7',
28 silly addNameRange     '0.0.8',
28 silly addNameRange     '0.0.9',
28 silly addNameRange     '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.2.1',
28 silly addNameRange     '0.2.2',
28 silly addNameRange     '0.2.3',
28 silly addNameRange     '0.2.4',
28 silly addNameRange     '0.2.5',
28 silly addNameRange     '0.2.6',
28 silly addNameRange     '0.2.7',
28 silly addNameRange     '0.2.8',
28 silly addNameRange     '0.2.9',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.3.21',
28 silly addNameRange     '0.3.3',
28 silly addNameRange     '0.3.4',
28 silly addNameRange     '0.3.5',
28 silly addNameRange     '0.3.6',
28 silly addNameRange     '0.3.7',
28 silly addNameRange     '0.3.8',
28 silly addNameRange     '0.3.9',
28 silly addNameRange     '0.3.11',
28 silly addNameRange     '0.3.13',
28 silly addNameRange     '0.3.14',
28 silly addNameRange     '0.3.15',
28 silly addNameRange     '0.3.16',
28 silly addNameRange     '0.3.17',
28 silly addNameRange     '0.3.18',
28 silly addNameRange     '0.3.19',
28 silly addNameRange     '0.3.20',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.4.1',
28 silly addNameRange     '0.4.2',
28 silly addNameRange     '0.4.3',
28 silly addNameRange     '0.4.4',
28 silly addNameRange     '0.4.5',
28 silly addNameRange     '0.4.6',
28 silly addNameRange     '0.4.7',
28 silly addNameRange     '0.4.8',
28 silly addNameRange     '0.4.9',
28 silly addNameRange     '0.4.10',
28 silly addNameRange     '0.4.12',
28 silly addNameRange     '0.4.13',
28 silly addNameRange     '0.4.14',
28 silly addNameRange     '0.4.15',
28 silly addNameRange     '0.4.16',
28 silly addNameRange     '0.4.17',
28 silly addNameRange     '0.4.18',
28 silly addNameRange     '0.4.19',
28 silly addNameRange     '0.4.20',
28 silly addNameRange     '0.4.21',
28 silly addNameRange     '0.4.22',
28 silly addNameRange     '0.4.23',
28 silly addNameRange     '0.4.24',
28 silly addNameRange     '0.4.25',
28 silly addNameRange     '0.4.26',
28 silly addNameRange     '0.4.27',
28 silly addNameRange     '0.4.28',
28 silly addNameRange     '0.4.29',
28 silly addNameRange     '0.4.30',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.5.1',
28 silly addNameRange     '0.5.2',
28 silly addNameRange     '0.5.3',
28 silly addNameRange     '0.5.4',
28 silly addNameRange     '0.5.5',
28 silly addNameRange     '0.5.6',
28 silly addNameRange     '0.5.7',
28 silly addNameRange     '0.5.8',
28 silly addNameRange     '0.5.9',
28 silly addNameRange     '0.5.10',
28 silly addNameRange     '0.5.11',
28 silly addNameRange     '0.5.12',
28 silly addNameRange     '0.5.13',
28 silly addNameRange     '0.5.14',
28 silly addNameRange     '0.5.15',
28 silly addNameRange     '0.5.16',
28 silly addNameRange     '0.5.17',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.6.1',
28 silly addNameRange     '0.6.2',
28 silly addNameRange     '0.6.3',
28 silly addNameRange     '0.6.4',
28 silly addNameRange     '0.6.5',
28 silly addNameRange     '0.6.6',
28 silly addNameRange     '0.6.7',
28 silly addNameRange     '0.5.18',
28 silly addNameRange     '0.5.19',
28 silly addNameRange     '0.5.20',
28 silly addNameRange     '0.5.21',
28 silly addNameRange     '0.0.45',
28 silly addNameRange     '0.5.22',
28 silly addNameRange     '0.5.23',
28 silly addNameRange     '0.5.24',
28 silly addNameRange     '0.5.25',
28 silly addNameRange     '0.5.26',
28 silly addNameRange     '0.5.27',
28 silly addNameRange     '0.5.28',
28 silly addNameRange     '0.5.29',
28 silly addNameRange     '0.5.30',
28 silly addNameRange     '0.5.31',
28 silly addNameRange     '0.5.32',
28 silly addNameRange     '0.5.33',
28 silly addNameRange     '0.5.34',
28 silly addNameRange     '0.5.36',
28 silly addNameRange     '0.5.37',
28 silly addNameRange     '0.5.38',
28 silly addNameRange     '0.5.39',
28 silly addNameRange     '0.5.40',
28 silly addNameRange     '0.6.8',
28 silly addNameRange     '0.6.9',
28 silly addNameRange     '0.6.11',
28 silly addNameRange     '0.6.12',
28 silly addNameRange     '0.6.13',
28 silly addNameRange     '0.6.14',
28 silly addNameRange     '0.6.15',
28 silly addNameRange     '0.6.16',
28 silly addNameRange     '0.6.17',
28 silly addNameRange     '0.7.0',
28 silly addNameRange     '0.7.1' ] ]
29 verbose addNamed meanio@0.7.1
30 silly addNamed semver.valid 0.7.1
31 silly addNamed semver.validRange 0.7.1
32 silly mapToRegistry name meanio
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry uri https://registry.npmjs.org/meanio
36 verbose addRemoteTarball https://registry.npmjs.org/meanio/-/meanio-0.7.1.tgz not in flight; adding
37 verbose addRemoteTarball [ 'https://registry.npmjs.org/meanio/-/meanio-0.7.1.tgz',
37 verbose addRemoteTarball   '60d45748680de0b614edb97307d288d8eb4f5a60' ]
38 info retry fetch attempt 1 at 11:16:40
39 info attempt registry request try #1 at 11:16:40
40 http fetch GET https://registry.npmjs.org/meanio/-/meanio-0.7.1.tgz
41 http fetch 200 https://registry.npmjs.org/meanio/-/meanio-0.7.1.tgz
42 silly fetchAndShaCheck shasum 60d45748680de0b614edb97307d288d8eb4f5a60
43 verbose addTmpTarball /tmp/npm-30459-94325063/registry.npmjs.org/meanio/-/meanio-0.7.1.tgz not in flight; adding
44 verbose addTmpTarball already have metadata; skipping unpack for meanio@0.7.1
45 silly cache afterAdd meanio@0.7.1
46 verbose afterAdd /home/ed/.npm/meanio/0.7.1/package/package.json not in flight; writing
47 verbose afterAdd /home/ed/.npm/meanio/0.7.1/package/package.json written
48 silly install resolved [ { name: 'meanio',
48 silly install resolved     version: '0.7.1',
48 silly install resolved     description: 'Extracted functionality for MEAN.io',
48 silly install resolved     author: { name: 'linnovate' },
48 silly install resolved     contributors: [ [Object], [Object], [Object], [Object] ],
48 silly install resolved     license: 'MIT',
48 silly install resolved     main: 'index',
48 silly install resolved     scripts:
48 silly install resolved      { preinstall: 'node ./scripts/preinstall',
48 silly install resolved        postinstall: 'cd ./lib/core_modules/server && npm install && cd ../../..' },
48 silly install resolved     repository: { type: 'git', url: 'https://github.com/linnovate/meanio.git' },
48 silly install resolved     keywords: [ 'mean', 'meanio', 'mean.io', 'mean-cli' ],
48 silly install resolved     engines: { node: '0.10.x', npm: '1.4.x' },
48 silly install resolved     dependencies:
48 silly install resolved      { 'complex-list': 'latest',
48 silly install resolved        'dependable-list': 'latest',
48 silly install resolved        'lazy-dependable': 'latest',
48 silly install resolved        glob: '^4.0.3',
48 silly install resolved        lodash: '^2.4.1',
48 silly install resolved        'mean-cli': '^0.9.6',
48 silly install resolved        'mean-health': '~0.1.3',
48 silly install resolved        q: '^1.0.1',
48 silly install resolved        request: '^2.47.0',
48 silly install resolved        swig: '^1.3.2',
48 silly install resolved        'uglify-js': '^2.4.14' },
48 silly install resolved     devDependencies:
48 silly install resolved      { grunt: '^0.4.4',
48 silly install resolved        'grunt-contrib-jshint': '^0.10.0',
48 silly install resolved        'grunt-mocha-test': '^0.10.0',
48 silly install resolved        mocha: '^1.18.2',
48 silly install resolved        should: '^3.2.0' },
48 silly install resolved     gitHead: 'debf0506864cc8e4fb2d4158dbebe6d4d97036e9',
48 silly install resolved     bugs: { url: 'https://github.com/linnovate/meanio/issues' },
48 silly install resolved     homepage: 'https://github.com/linnovate/meanio',
48 silly install resolved     _id: 'meanio@0.7.1',
48 silly install resolved     _shasum: '60d45748680de0b614edb97307d288d8eb4f5a60',
48 silly install resolved     _from: 'meanio@*',
48 silly install resolved     _npmVersion: '2.1.18',
48 silly install resolved     _nodeVersion: '0.10.35',
48 silly install resolved     _npmUser: { name: 'andrija-hers', email: 'andrija.hers@gmail.com' },
48 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object] ],
48 silly install resolved     dist:
48 silly install resolved      { shasum: '60d45748680de0b614edb97307d288d8eb4f5a60',
48 silly install resolved        tarball: 'http://registry.npmjs.org/meanio/-/meanio-0.7.1.tgz' },
48 silly install resolved     directories: {},
48 silly install resolved     _resolved: 'https://registry.npmjs.org/meanio/-/meanio-0.7.1.tgz' } ]
49 info install meanio@0.7.1 into /home/localhost
50 info installOne meanio@0.7.1
51 verbose installOne of meanio to /home/localhost not in flight; installing
52 warn locking Error: EACCES, open '/home/ed/.npm/_locks/meanio-15d2ed50d94ce019.lock'
52 warn locking  /home/ed/.npm/_locks/meanio-15d2ed50d94ce019.lock failed { [Error: EACCES, open '/home/ed/.npm/_locks/meanio-15d2ed50d94ce019.lock']
52 warn locking   errno: 3,
52 warn locking   code: 'EACCES',
52 warn locking   path: '/home/ed/.npm/_locks/meanio-15d2ed50d94ce019.lock' }
53 verbose stack Error: Attempt to unlock /home/localhost/node_modules/meanio, which hasn't been locked
53 verbose stack     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:66:11)
53 verbose stack     at cb (/usr/lib/node_modules/npm/lib/install.js:929:5)
53 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:933:20
53 verbose stack     at /usr/lib/node_modules/npm/lib/utils/locker.js:40:9
53 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
53 verbose stack     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
53 verbose stack     at Object.oncomplete (fs.js:107:15)
54 verbose cwd /home/localhost/leed
55 error Linux 3.13.0-44-generic
56 error argv "node" "/usr/bin/npm" "install" "meanio"
57 error node v0.10.33
58 error npm  v2.4.1
59 error Attempt to unlock /home/localhost/node_modules/meanio, which hasn't been locked
60 error If you need help, you may report this error at:
60 error     <http://github.com/npm/npm/issues>
61 verbose exit [ 1, true ]

**Comment by liorkesos** [comment]
All f those EACCESS look like a permissions error. Please make sure you're
installing as a penal v user and that your ~/.npm directory does not have
any root permmisioned directories.
Chown your username -R ~/.npm might do the trick
Lior

**Comment by Maiti** [comment]
thank you very much

**Comment by emraanzaki** [comment]
You saved my day, thanks
