### ISSUE TITLE
modulePath used without definition in meanio/lib/core_modules/module/index.js

### ISSUE THREAD

**Issue by skwsk** [linnovate/meanio#42]
I'm new for nodejs so this may be just failure of my setup. In that case, please ignore this one.

I just start study for MEAN and node.js. I did setup mean-cli and create custom package by "mean package <pkg-name>". Then, it works but one of the pre-built link in the custom package doesn't work. It seems the cause of failure is that "modulePath" is used in render method of "meanio/lib/core_modules/module/index.js" without definition. I did replace it with another method and it seems working. Again, I'm new for nodejs so can be wrong and just my mistake for the setup.

**Comment by hyakinthos** [comment]
+1

**Comment by danielskapunk** [comment]
With wich method did you replace it, I'm having a problem with that method too.
Thanks.

**Comment by skwsk** [comment]
Again, I'm new for JS so this can be bad way. Anyway, the following change is working for me. 

node_modules/meanio/lib/core_modules/module/index.js

162c162,163
<     swig.renderFile(modulePath(this.name, '/server/views/' + view + '.html'), options, callback);
---
>     //swig.renderFile(modulePath(this.name, '/server/views/' + view + '.html'), options, callback);
>     swig.renderFile(this.loadedmodule.path('server') + '/views/' + view + '.html', options, callback);

**Comment by danielskapunk** [comment]
thanks, that worked for me too ;)

**Comment by antoinegomez** [comment]
I am new too, just installed and created a custom package and I got this error.

Ran a quick $ grep -r "modulePath(" . and this is the only occurence of this function call. Doing a merge request to replace it.

**Comment by liorkesos** [comment]
Fixed. Closing.
