### ISSUE TITLE
config getSettings doesn't work

### ISSUE THREAD

**Issue by vmartis** [linnovate/meanio#49]
Config.prototype.getSettings - Package from return of Config.prototype.getSettings is allways undefined.

Rewrite it to callback

Config.prototype.getSettings = function(name, callback) {
  this.loadPackageModel(function(Package) {
      if (!Package){
        return callback ? callback(new Error('Failed to retrieve settings')) : undefined;
      }
      Package.findOne({
        name: name
      }, function(err, doc) {
        if (err) {
          console.log(err);
          return callback(new Error('Failed to retrieve settings'));
        }
        return callback(null, doc);
      });
  });
};

**Comment by clowenhg** [comment]
@timelf123 @liorkesos Can close since update to `config` npm module
