### ISSUE TITLE
 Error: ENOENT when deploy to Heroku

### ISSUE THREAD

**Issue by davecyen** [linnovate/meanio#50]
I'm encountering an error that causes my heroku deployments to fail:

 Error: ENOENT, no such file or directory '/app/bower_components/jquery/dist/jquery.min.map'

Prior to deploying, I've tried various combinations of bower install, bower cache clean, npm cache clean, and npm install. Sometimes it will successfully deploy, other times it will fail. I haven't been able to find a consistent solution - appears random. Has anyone else encountered this issue?

**Comment by davecyen** [comment]
I tried to run "npm install --allow-root" as suggested in the FAQ, but no luck (https://github.com/linnovate/mean/wiki/Faq). Can anyone help?

**Comment by clowenhg** [comment]
Latest versions of Mean are using webpack, which removes the need for `bower_components`
