### ISSUE TITLE
How to turn off Stacksight

### ISSUE THREAD

**Issue by timelf123** [linnovate/meanio#96]
The events system seems to be tied directly to stacksight. Is there a way to disable sending events to sts?

**Comment by liorkesos** [comment]
We're working on disabling it alltogether.
In the meantime I think running *mean disable user-reporting *should stop
it.
Lior

On Wed, Feb 3, 2016 at 10:08 PM, Tim Elfelt <notifications@github.com>
wrote:

> The events system seems to be tied directly to stacksight. Is there a way
> to disable sending events to sts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/meanio/issues/96>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by timelf123** [comment]
Thanks @liorkesos
